services:
  db:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf
      MYSQL_USER: db_user
      MYSQL_PASSWORD: asdfasdf
      MYSQL_DATABASE: gaming_service
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
